#---------------------------------#
#      environment configuration  #
#---------------------------------#
version: 1.0.{build}
image: WMF 5

#---------------------------------#
#      install configuration      #
#---------------------------------#
install:
    - ps: |
        Write-Host "Install prerequisites" -ForegroundColor Yellow
        $null = Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force -ErrorAction Stop
        Install-Module -Name PSScriptAnalyzer -Repository PSGallery -Force -ErrorAction Stop
        Install-Module -Name Pester -Repository PSGallery -Force -ErrorAction Stop
        # Validate
        $RequiredModules = 'PSScriptAnalyzer','Pester'
        $InstalledModules = Get-Module -Name $RequiredModules -ListAvailable
        Write-Host "Installed modules:" -ForegroundColor Yellow
        $InstalledModules | ft Name, Version
        if ( ($InstalledModules.count -lt $RequiredModules.Count) -or ($Null -eq $InstalledModules)) {
            throw "Required modules are missing."
        } else {
            Write-Host "All required modules found!" -ForegroundColor Green
        }

#---------------------------------#
#      build configuration        #
#---------------------------------#
build: false

#---------------------------------#
#      test configuration         #
#---------------------------------#
test_script:
    - ps: |
        Write-Host "Running Test script" -ForegroundColor Yellow
        Invoke-AppveyorTestScriptTask
